_wandb:
    value:
        cli_version: 0.25.0
        e:
            sstr68puuacub1upx8fou0encjo1wj7q:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "9663676416"
                codePath: scripts/wandb/weave_eval_runner.py
                codePathLocal: scripts/wandb/weave_eval_runner.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "477125672960"
                email: yajima.code@gmail.com
                executable: /Users/yajima/.cache/uv/archive-v0/e--aBG0WZe2anlGPZuNxG/bin/python3
                git:
                    commit: 06db4185bef07edbf7a5ddf581008190617b406c
                    remote: git@github.com:Haruk1y/Mistral_Hackathon.git
                host: yajimayoujunoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/yajima/Desktop/dev/Mistral_Hackathon/scripts/wandb/weave_eval_runner.py
                python: CPython 3.12.2
                root: /Users/yajima/Desktop/dev/Mistral_Hackathon
                startedAt: "2026-02-28T23:15:44.555988Z"
                writerId: sstr68puuacub1upx8fou0encjo1wj7q
        m: []
        python_version: 3.12.2
        t:
            "3":
                - 15
                - 16
            "4": 3.12.2
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
dataset_path:
    value: artifacts/eval/tmp_eval_2.json
fine_tuned_model_id:
    value: ""
large_model_id:
    value: ""
mode:
    value: prompt_baseline
prompt_model_id:
    value: ""
target_scale:
    value: 10
