_wandb:
    value:
        cli_version: 0.25.0
        e:
            9cfggdmamdjf2fuha7q51r3a0pzkuk5a:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "7516192768"
                codePath: scripts/wandb/weave_eval_runner.py
                codePathLocal: scripts/wandb/weave_eval_runner.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "478700552192"
                email: yajima.code@gmail.com
                executable: /Users/yajima/Desktop/dev/Mistral_Hackathon/.uv-cache/archive-v0/FWcWYSj17erIgrA6RKqdb/bin/python3
                git:
                    commit: 1733ce11e65938435908e2801f6f4f18d33bdae0
                    remote: git@github.com:Haruk1y/Mistral_Hackathon.git
                host: yajimayoujunoMacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/yajima/Desktop/dev/Mistral_Hackathon/scripts/wandb/weave_eval_runner.py
                python: CPython 3.12.2
                root: /Users/yajima/Desktop/dev/Mistral_Hackathon
                startedAt: "2026-02-28T17:43:02.555975Z"
                writerId: 9cfggdmamdjf2fuha7q51r3a0pzkuk5a
        m: []
        python_version: 3.12.2
        t:
            "3":
                - 15
                - 16
            "4": 3.12.2
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
dataset_path:
    value: data/eval/test_eval_set.from_ft_test.v1.json
fine_tuned_model_id:
    value: ""
large_model_id:
    value: ""
mode:
    value: prompt_baseline
prompt_model_id:
    value: mistralai/Ministral-3-3B-Instruct-2512
target_scale:
    value: 10
